### ISSUE TITLE
Failed: key not found: "ram" during compiling

### ISSUE THREAD

**Issue by liuxiaoxi2237** [cloudfoundry-community/cf-services-contrib-release#155]
When deploy contrib serice v6, errors in compiling as below:
Started compiling packages
  Started compiling packages > rootfs_lucid64/9b3f611b46e076b94b37645c98f9100e7bcef5dd
  Started compiling packages > postgresql93/06163819b694f8d9836586d024f64c11efe30180
  Started compiling packages > postgresql92/2867893e714aae6e6b76bd06e7aa30d47023c46e. Failed: key not found: "ram" (00:00:00)
   Failed compiling packages > rootfs_lucid64/9b3f611b46e076b94b37645c98f9100e7bcef5dd: key not found: "ram" (00:00:00)
   Failed compiling packages > postgresql93/06163819b694f8d9836586d024f64c11efe30180: key not found: "ram" (00:00:00)

Bosh log as below:
I, [2015-08-05 16:55:55 #17795] [compile_package(postgresql92/2867893e714aae6e6b76bd06e7aa30d47023c46e, bosh-vsphere-esxi-ubuntu-trusty-go_agent/3012)]  INFO -- DirectorJobRunner: Package `postgresql92/2867893e714aae6e6b76bd06e7aa30d47023c46e' needs to be compiled on `bosh-vsphere-esxi-ubuntu-trusty-go_agent/3012'
D, [2015-08-05 16:55:55 #17795] [compile_package(postgresql93/06163819b694f8d9836586d024f64c11efe30180, bosh-vsphere-esxi-ubuntu-trusty-go_agent/3012)] DEBUG -- DirectorJobRunner: (0.001169s) SELECT NULL
D, [2015-08-05 16:55:55 #17795] [compile_package(postgresql92/2867893e714aae6e6b76bd06e7aa30d47023c46e, bosh-vsphere-esxi-ubuntu-trusty-go_agent/3012)] DEBUG -- DirectorJobRunner: (0.000314s) SELECT NULL
D, [2015-08-05 16:55:55 #17795] [compile_package(rootfs_lucid64/9b3f611b46e076b94b37645c98f9100e7bcef5dd, bosh-vsphere-esxi-ubuntu-trusty-go_agent/3012)] DEBUG -- DirectorJobRunner: Deleted lock: lock:compile:90:1
D, [2015-08-05 16:55:55 #17795] [] DEBUG -- DirectorJobRunner: Worker thread raised exception: key not found: "ram" - /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_vsphere_cpi-1.3012.0/lib/cloud/vsphere/vm_creator_builder.rb:7:in `fetch'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_vsphere_cpi-1.3012.0/lib/cloud/vsphere/vm_creator_builder.rb:7:in `build'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_vsphere_cpi-1.3012.0/lib/cloud/vsphere/cloud.rb:158:in `block in create_vm'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3012.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_vsphere_cpi-1.3012.0/lib/cloud/vsphere/cloud.rb:157:in `create_vm'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3012.0/lib/bosh/director/vm_creator.rb:41:in `create'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3012.0/lib/bosh/director/vm_creator.rb:9:in `create'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3012.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:153:in `prepare_vm'

Any suggestions,thanks.

**Comment by rkoster** [comment]
Could it be that you are deploying on vsphere and forgot to specify `ram` in your resource pool? If so relevant documentation can be found [here](https://bosh.io/docs/vsphere-cpi.html#resource-pools).
