### ISSUE TITLE
bosh create release failure

### ISSUE THREAD

**Issue by zhoutiekui** [cloudfoundry-community/cf-services-contrib-release#173]
when i exec  bosh create release command,there is an error Blobstore error: Could not fetch object, 403. is there anybody who knows the reason ? thanks

root@bosh-client:/cf/databases/cf-services-contrib-release# bosh create release
Syncing blobs...
erlang/otp_src_R14B01.tar.gz downloading 61.8M (0%)
RSA 1024 bit CA certificates downloading 61.8M (0%)
/usr/local/lib/ruby/gems/2.2.0/gems/blobstore_client-1.3262.0/lib/blobstore_client/simple_blobstore_client.rb:44:in `get_file': Could not fetch object, 403/ (Bosh::Blobstore::BlobstoreError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/blobstore_client-1.3262.0/lib/blobstore_client/s3_blobstore_client.rb:79:in `get_file'
	from /usr/local/lib/ruby/gems/2.2.0/gems/blobstore_client-1.3262.0/lib/blobstore_client/base.rb:50:in `get'
	from /usr/local/lib/ruby/gems/2.2.0/gems/blobstore_client-1.3262.0/lib/blobstore_client/sha1_verifiable_blobstore_client.rb:19:in `get'
	from /usr/local/lib/ruby/gems/2.2.0/gems/blobstore_client-1.3262.0/lib/blobstore_client/retryable_blobstore_client.rb:19:in `block in get'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bosh_common-1.3262.0/lib/common/retryable.rb:28:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bosh_common-1.3262.0/lib/common/retryable.rb:28:in `block in retryer'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bosh_common-1.3262.0/lib/common/retryable.rb:26:in `loop'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bosh_common-1.3262.0/lib/common/retryable.rb:26:in `retryer'
	from /usr/local/lib/ruby/gems/2.2.0/gems/blobstore_client-1.3262.0/lib/blobstore_client/retryable_blobstore_client.rb:18:in `get'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bosh_cli-1.3262.0/lib/cli/blob_manager.rb:316:in `download_blob'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bosh_cli-1.3262.0/lib/cli/blob_manager.rb:242:in `block (3 levels) in process_index'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bosh_common-1.3262.0/lib/common/thread_pool.rb:77:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bosh_common-1.3262.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bosh_common-1.3262.0/lib/common/thread_pool.rb:63:in `loop'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bosh_common-1.3262.0/lib/common/thread_pool.rb:63:in `block in create_thread'
	from /usr/local/lib/ruby/gems/2.2.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
root@bosh-client:/cf/databases/cf-services-contrib-release# bosh create release releases/cf-services-contrib-6.yml 
Recreating release from the manifest
Downloading from blobstore (id=6907fc2f-c321-4593-ae60-4fdab2866be8)...
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Blobstore error: Could not fetch object, 403/
root@bosh-client:/cf/databases/cf-services-contrib-release#

**Comment by nunodio** [comment]
You can create the release using : 

`bosh upload release https://bosh.io/d/github.com/cloudfoundry-community/cf-services-contrib-release?v=6`

instead:

`bosch create release` 

Hope it can help you.

**Comment by lewiseevans** [comment]
Is there any update on this? 

It's not suitable for us to use the upload release and we specifically need to create it.

**Comment by andrew-edgar** [comment]
Can you please give us some feedback on this item.  We need to create the release in our case and just uploading it from bosh.io is not sufficient!

**Comment by rkoster** [comment]
I'm unable to login to the aws account which created the bucket (this account was provided by pivotal).
